import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { UserButton } from "@neondatabase/auth/react/ui";
import { Providers } from "@/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <header className="bg-slate-800 border-slate-700 rounded-lg shadow-lg">
            <div className="flex flex row px-2 py-6 justify-between items-center">
              <Link href={"/"}>PlanIt</Link>
              <nav className="flex item-center gap-4">
                <Link href={"/dashboard"} className="text-sm text-slate-300">
                  Dashboard
                </Link>
                <UserButton size="icon" />
              </nav>
            </div>
          </header>
          <main className="flex-1 mx-auto w-full max-w-6xl flex-col px-6 py-4">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
