import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { UserButton } from "@neondatabase/auth/react/ui";
import { Providers } from "@/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <header className="sticky top-4 z-50 w-full max-w-6xl mx-auto px-4 sm:px-6 mt-2">
            <div className="flex items-center justify-between px-6 py-3 bg-slate-900/60 border border-slate-700/50 rounded-full shadow-[0_8px_30px_rgb(0,0,0,0.12)] backdrop-blur-md">
              <Link href="/" className="text-xl font-extrabold tracking-tight text-white hover:text-slate-200 transition-colors">
                PlanIt.
              </Link>
              <nav className="flex items-center gap-6">
                <Link href="/dashboard" className="text-sm font-medium text-slate-300 hover:text-white transition-colors">
                  Dashboard
                </Link>
                <div className="h-5 w-px bg-slate-700/60 hidden sm:block" />
                <UserButton size="icon" />
              </nav>
            </div>
          </header>
          <main className="flex-1 mx-auto w-full max-w-6xl flex-col px-6 py-4">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
